# Server Port (Railway/Render usually provide this automatically, but 8080 is safe)
server.port=8080

# Neon Database
spring.datasource.url=jdbc:postgresql://ep-blue-rain-ad7lpm81-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_2vK0EYaDHIqW

# Production Optimization
spring.jpa.hibernate.ddl-auto=update
spring.thymeleaf.cache=true